"""add_subtasks_to_habits

Revision ID: 4c62edab0f80
Revises: 6505869d764c
Create Date: 2026-06-18 13:14:33.566330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c62edab0f80'
down_revision: Union[str, None] = '6505869d764c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_habit_logs', sa.Column('completed_subtasks', sa.Text(), nullable=True))
    op.add_column('daily_habits', sa.Column('subtasks', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_habits', 'subtasks')
    op.drop_column('daily_habit_logs', 'completed_subtasks')
    # ### end Alembic commands ###
